name: linux-build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake 3.18
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: 3.18

    - name: Install GCC 11
      run: |
          sudo apt-get install gcc-11 g++-11

    - name: Install gcovr
      run: |
        pip3 install gcovr

    - name: Build
      run: |
          cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D LAPLACE_ENABLE_TESTING=ON -D LAPLACE_ENABLE_COVERAGE=ON -D LAPLACE_VERBOSE=ON -B build -S .
          cmake --build build --config $BUILD_TYPE
      env:
        CC: gcc-11
        CXX: g++-11

    - name: Run tests & generate coverage
      working-directory: ${{github.workspace}}/build
      run: |
        ctest -V -C $BUILD_TYPE
        ~/.local/bin/gcovr -j $(nproc) --delete --root ../source/ --exclude '\.\./source/test/' --print-summary --xml-pretty --xml coverage.xml .

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ${{github.workspace}}/build/coverage.xml
        fail_ci_if_error: true
