name: linux-build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake 3.18
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: 3.18

    - name: Build
      run: |
          cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D LAPLACE_ENABLE_TESTING=ON -B build -S .
          cmake --build build --config $BUILD_TYPE
      env:
        CC: gcc-10
        CXX: g++-10

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest -V -C $BUILD_TYPE
